.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gthpcoin_qt test_gthpcoin_qt
clean: FORCE
	$(MAKE) -C .. gthpcoin_qt_clean test_gthpcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_gthpcoin_qt_check
gthpcoin-qt gthpcoin-qt.exe: FORCE
	 $(MAKE) -C .. gthpcoin_qt
